[@data.table id="myTable" entries=people]
	[@column title="First Name"]${entry.firstName}[/@column]
	[@column title="Last Name"]${entry.lastName}[/@column]
	[@column title="Birthday" format="date"]${entry.birthday?jsDate}[/@column]
[/@data.table]
